name: Sync Production to Public Repository

on:
  push:
    branches: [ produccion ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        ref: produccion
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone public repository
      run: |
        git clone https://${{ secrets.GH_TOKEN }}@github.com/xerchion/portfolio-web.git public-repo

    - name: Sync files
      run: |
        find public-repo -mindepth 1 -name '.git' -prune -o -type f -delete
        find public-repo -mindepth 1 -name '.git' -prune -o -type d -empty -delete
        cp -r index.html public-repo/
        cp -r doc-algoritmo.html public-repo/
        cp -r assets/ public-repo/

    - name: Create README
      run: |
        echo "# Portfolio Web" > public-repo/README.md
        echo "" >> public-repo/README.md
        echo "Portfolio web profesional desarrollado con tecnologías modernas." >> public-repo/README.md
        echo "" >> public-repo/README.md
        echo "Ver en vivo: https://xerchion.github.io/portfolio-web/" >> public-repo/README.md
        echo "" >> public-repo/README.md
        echo "## Tecnologías" >> public-repo/README.md
        echo "" >> public-repo/README.md
        echo "- HTML5, CSS3, JavaScript" >> public-repo/README.md
        echo "- Tailwind CSS" >> public-repo/README.md
        echo "- Diseño responsivo" >> public-repo/README.md

    - name: Commit and push to public repo
      run: |
        cd public-repo
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "Actualización automática desde repositorio privado"
          git push origin main
          echo "Cambios sincronizados exitosamente"
        else
          echo "No hay cambios para sincronizar"
        fi